### ISSUE TITLE
Xamarin iOS

### ISSUE THREAD

**Issue by ibiren** [evermeer/PassportScanner#15]
Can we bind this scanner to Xamarin iOS, as it is being developed in swift

**Comment by evermeer** [comment]
I don't know, I have no experience using Xamarin. Since you can still use Swift and Objective C code in Xamarin, I do think you could use PassportScanner in a Xamarin project. 

But it could be a bit tricky since PassportScanner has the following 4 libraries as a dependency:
TesseractOCRiOS, GPUImage, UIImage-Resize and EVGPUImage2

**Comment by evermeer** [comment]
It looks like it's possible to use swift libraries in Xamarin. 

For more info see:
https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76
and https://forums.xamarin.com/discussion/63657/binding-swift-code

I'm closing this issue since this is actually about how to use Swift in Xamarin and not about Passportscnner.

**Comment by ibiren** [comment]
I agree this is not a issue. Can you suggest me ways to implement this code in Objective C project
