### ISSUE TITLE
How can I add  in Objective-C Project

### ISSUE THREAD

**Issue by jassimkm** [evermeer/PassportScanner#40]
Can you provide piece of code to integrate it in objective-c project

**Comment by evermeer** [comment]
Since objective C and Swift could be mixed in one project I would advice to create the passport scanner part in Swift.

I think it's possible to call it from objective C but I have never tried it. For doing that I think you should create a variant of the MyScanViewController that you see in the sample and call that from a class that works a little like the ViewController that you also see there. Just create functions and properties with the same signatures.

**Comment by evermeer** [comment]
If you have any more questions, then don't hesitate to ask.
